### ISSUE TITLE
C++ bindings compile error

### ISSUE THREAD

**Issue by hesmar** [eclipse-iceoryx/iceoryx2#855]
## Required information

**Operating system:**

Ubuntu 20.04.6 LTS
Linux ecm-unknown 4.9.337-l4t-r32.7.6+g44ff95afac8e #1 SMP PREEMPT Fri Apr 25 11:09:12 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

**Rust version:**
rustc 1.87.0 (17067e9ac 2025-05-09)

**Cargo version:**
cargo 1.87.0 (99624be96 2025-05-06)

**iceoryx2 version:**
main

**Detailed log output:**
```
In file included from /home/3dvl/workspace/libs/iceoryx2/iceoryx2-build/_deps/iceoryx-src/iceoryx_hoofs/vocabulary/include/iox/string.hpp:20,
                 from /home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/attribute.hpp:16,
                 from /home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/src/attribute.cpp:13:
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp: In function 'constexpr typename iox::detail::extract_into_type<DestinationType>::type_t iox::from(SourceType) [with SourceType = int; DestinationType = iox2::SemanticStringError; typename iox::detail::extract_into_type<DestinationType>::type_t = iox2::SemanticStringError]':
/home/3dvl/workspace/libs/iceoryx2/iceoryx2-build/_deps/iceoryx-src/iceoryx_hoofs/reporting/include/iox/assertions.hpp:83:26: error: call to non-'constexpr' function 'void iox::er::forwardPanic(const iox::er::SourceLocation&, Message&&) [with Message = const char (&)[50]]'
     iox::er::forwardPanic(IOX_CURRENT_SOURCE_LOCATION, "Reached code that was supposed to be unreachable.")
     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp:56:5: note: in expansion of macro 'IOX_UNREACHABLE'
     IOX_UNREACHABLE();
     ^~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp: In function 'constexpr typename iox::detail::extract_into_type<DestinationType>::type_t iox::from(SourceType) [with SourceType = iox2::SemanticStringError; DestinationType = iox2_semantic_string_error_e; typename iox::detail::extract_into_type<DestinationType>::type_t = iox2_semantic_string_error_e]':
/home/3dvl/workspace/libs/iceoryx2/iceoryx2-build/_deps/iceoryx-src/iceoryx_hoofs/reporting/include/iox/assertions.hpp:83:26: error: call to non-'constexpr' function 'void iox::er::forwardPanic(const iox::er::SourceLocation&, Message&&) [with Message = const char (&)[50]]'
     iox::er::forwardPanic(IOX_CURRENT_SOURCE_LOCATION, "Reached code that was supposed to be unreachable.")
     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp:70:5: note: in expansion of macro 'IOX_UNREACHABLE'
     IOX_UNREACHABLE();
     ^~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp: In function 'constexpr typename iox::detail::extract_into_type<DestinationType>::type_t iox::from(SourceType) [with SourceType = int; DestinationType = iox2::ServiceType; typename iox::detail::extract_into_type<DestinationType>::type_t = iox2::ServiceType]':
/home/3dvl/workspace/libs/iceoryx2/iceoryx2-build/_deps/iceoryx-src/iceoryx_hoofs/reporting/include/iox/assertions.hpp:83:26: error: call to non-'constexpr' function 'void iox::er::forwardPanic(const iox::er::SourceLocation&, Message&&) [with Message = const char (&)[50]]'
     iox::er::forwardPanic(IOX_CURRENT_SOURCE_LOCATION, "Reached code that was supposed to be unreachable.")
     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp:89:5: note: in expansion of macro 'IOX_UNREACHABLE'
     IOX_UNREACHABLE();
     ^~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp: In function 'constexpr typename iox::detail::extract_into_type<DestinationType>::type_t iox::from(SourceType) [with SourceType = iox2::ServiceType; DestinationType = iox2_service_type_e; typename iox::detail::extract_into_type<DestinationType>::type_t = iox2_service_type_e]':
/home/3dvl/workspace/libs/iceoryx2/iceoryx2-build/_deps/iceoryx-src/iceoryx_hoofs/reporting/include/iox/assertions.hpp:83:26: error: call to non-'constexpr' function 'void iox::er::forwardPanic(const iox::er::SourceLocation&, Message&&) [with Message = const char (&)[50]]'
     iox::er::forwardPanic(IOX_CURRENT_SOURCE_LOCATION, "Reached code that was supposed to be unreachable.")
     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp:102:5: note: in expansion of macro 'IOX_UNREACHABLE'
     IOX_UNREACHABLE();
     ^~~~~~~~~~~~~~~
/home/3dvl/workspace/libs/iceoryx2/iceoryx2/iceoryx2-ffi/cxx/include/iox2/enum_translation.hpp: In function 'constexpr typename iox::detail::extract_into_type<DestinationType>::type_t iox::from(SourceType) [with SourceType = int; DestinationType = iox2::NodeCreationFailure; typename iox::detail::extract_into_type<DestinationType>::type_t = iox2::NodeCreationFailure]':
/home/3dvl/workspace/libs/iceoryx2/iceoryx2-build/_deps/iceoryx-src/iceoryx_hoofs/reporting/include/iox/assertions.hpp:83:26: error: call to non-'constexpr' function 'void iox::er::forwardPanic(const iox::er::SourceLocation&, Message&&) [with Message = const char (&)[50]]'
     iox::er::forwardPanic(IOX_CURRENT_SOURCE_LOCATION, "Reached code that was supposed to be unreachable.")
     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
--> MORE ERRORS HERE <---
...
make[2]: *** [iceoryx2-ffi/cxx/CMakeFiles/iceoryx2-cxx-object-lib.dir/build.make:76: iceoryx2-ffi/cxx/CMakeFiles/iceoryx2-cxx-object-lib.dir/src/attribute.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1070: iceoryx2-ffi/cxx/CMakeFiles/iceoryx2-cxx-object-lib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Observed result or behaviour:**
Compile error because IOX_UNREACHABLE() is not `constexpr`, but calling function is `constexpr`.

**Expected result or behaviour:**
C++ binding compilation should work.

**Conditions where it occurred / Performed steps:**
I followed instructions for building the C++ bindings.

**Comment by elBoberido** [comment]
@hesmar your assessment is correct. It seems newer compiler can detect that the switch-case ist exhaustive and therefore optimizes that call away to preserve the constexpr. Which compiler are your using. I have an idea on how to easily fix the problem, but I need to reproduce the error first.

**Comment by hesmar** [comment]
I use gcc/g++. Version is 9.4.0.

**Comment by elBoberido** [comment]
Of course it's the one which is not available on Arch 😅

**Comment by elBoberido** [comment]
@hesmar I tried to build iceoryx2 on Ubuntu 20.04 with gcc 9.4 but I was not able to reproduce the error. Do you have more information about your setup?

**Comment by hesmar** [comment]
@elBoberido Ah... compiler version was wrong. We pinned gcc version to 8.4.0 globally, because we use CUDA 10.2 on Nvidia Jetson and that is only compatible with gcc<=8.x. So the issue here is related to gcc 8 not 9. Sorry for that.

With gcc 9, I got another error:
```
[  0%] Built target iceoryx2-build-step
[  0%] Building C object examples/c/discovery/CMakeFiles/example_c_discovery.dir/src/main.c.o
[  1%] Linking C executable example_c_discovery
[  1%] Built target example_c_discovery
[  1%] Building C object examples/c/domains/CMakeFiles/example_c_domains_publisher.dir/src/publisher.c.o
[  2%] Linking C executable example_c_domains_publisher
/usr/bin/ld: ../../../rust/native/release/libiceoryx2_ffi.a(iceoryx2_pal_posix-215f632bc2e11e5b.iceoryx2_pal_posix.e889f182ce09a18b-cgu.1.rcgu.o): in function `iceoryx2_pal_posix::platform::mman::shm_open':
iceoryx2_pal_posix.e889f182ce09a18b-cgu.1:(.text._ZN18iceoryx2_pal_posix8platform4mman8shm_open17h33bd44627af4e123E+0x0): undefined reference to `shm_open'
/usr/bin/ld: ../../../rust/native/release/libiceoryx2_ffi.a(iceoryx2_pal_posix-215f632bc2e11e5b.iceoryx2_pal_posix.e889f182ce09a18b-cgu.1.rcgu.o): in function `iceoryx2_pal_posix::platform::mman::shm_unlink':
iceoryx2_pal_posix.e889f182ce09a18b-cgu.1:(.text._ZN18iceoryx2_pal_posix8platform4mman10shm_unlink17h8a1b95e387e3fe9cE+0x0): undefined reference to `shm_unlink'
/usr/bin/ld: ../../../rust/native/release/libiceoryx2_ffi.a(std-70a67151a7e3ef69.std.121563b87310a60c-cgu.0.rcgu.o): in function `std::sys::pal::unix::weak::fetch':
/rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/sys/pal/unix/weak.rs:141: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/c/domains/CMakeFiles/example_c_domains_publisher.dir/build.make:98: examples/c/domains/example_c_domains_publisher] Error 1
make[1]: *** [CMakeFiles/Makefile2:678: examples/c/domains/CMakeFiles/example_c_domains_publisher.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I could solve this by adding `$<$<PLATFORM_ID:Linux>:dl rt>` to the `target_link_libraries` of the `static-lib` target in `iceoryx2-ffi/c/CMakeLists.txt`. After that, compilation was working with gcc 9.4.

**Comment by AmazingPP** [comment]
> I could solve this by adding `$<$<PLATFORM_ID:Linux>:dl rt>` to the `target_link_libraries` of the `static-lib` target in `iceoryx2-ffi/c/CMakeLists.txt`. After that, compilation was working with gcc 9.4.

@hesmar Hey, I hit the same problem on Debian 11 with GCC 10.2.1. Your fix (adding `dl rt`) worked perfectly. Huge thanks for posting this!

**Comment by elBoberido** [comment]
@hesmar do you want to create a pull request for the linker issue?

I'try to look into the gcc 8 issue the next days. Currently on the road.

**Comment by elBoberido** [comment]
@hesmar my idea worked but it is probably violating the C++ standard. My C++ got a bit rusty

@ComicSansMS the issue is that we use a `UNREACHABLE` macro in a `constexpr` function which translates from one enum class to another. The switch-case statement is exhaustive and the `UNREACHABLE` macro should never be called if the user did not do some invalid stuff like casting 123 to an enum class with the values 0, 1 and 2. So the `UNREACHABLE` macro is just there to catch such a situation without having a default case. We'd like to omit the default case, in order to have the compiler complain when a new tag is added to an enum which then also needs to be handled in the conversion.

The issue is now that the function that is wrapped with the `UNREACHABLE` macro is not `constexpr`. It seems gcc 9 and newer (as well as clang and MSVC) are able to figure out that the macro is never called in that context and optimize it away. gcc 8 on the other is not able to do it. The obvious solution would be no make the functions with the enum translation also not `constexpr` but I'd like to have my cake and eat it too. If the function behind the `UNREACHABLE` macro is made `constexpr`, then gcc 8 is also able to optimize that function away, although it would not be able to call it at compile time. AFAIK, this is against the C++ standard but so is our current code with the `UNREACHABLE` macro. Do you maybe have an idea how to solve this problem? Bonus points if you can do it with C++14.

**Comment by ComicSansMS** [comment]
@elBoberido This looks like a bug in gcc 8. It seems that the control flow analyzer is unable to determine that there are feasible execution paths that don't reach the end of the function where the `IOX_UNREACHABLE()` call happens. I am pretty sure that this is valid C++14 and should work.

It seems that gcc 8 can be convinced that there are paths which do not hit the `IOX_UNREACHABLE()` by moving it into a `default` case, instead of the end of the function. See [this example on godbolt](https://godbolt.org/z/4WjvzE5ha).

**Comment by elBoberido** [comment]
@ComicSansMS yeah, that would work but ideally we would get away without the default case. I have an idea to try out. Maybe I can hide the non constexpr code behind a code path which not even theoretically can be executed at compile time because a static_assert would be triggert first.

**Comment by ComicSansMS** [comment]
@elBoberido Ah, now I understand what you want. Sorry, I did not understand why you did not want the `default` at first. Yes, you can confuse the compiler by complicating the path on which the call to unreachable function happens. This is a bit fiddly, as it depends heavily on compiler internals and will likely look somewhat weird, but workarounds for compiler bugs often do.

See [this modified example](https://godbolt.org/z/eGqYcWKcG).

**Comment by elBoberido** [comment]
@ComicSansMS nice. I [modified the example](https://godbolt.org/z/7hKWMqndM) a little bit. If this is still allowed and not against the C++ standard, then my original idea by just making the [forwardPanic](https://github.com/eclipse-iceoryx/iceoryx/blob/main/iceoryx_hoofs/reporting/include/iox/error_reporting/error_forwarding.hpp#L41) function `constexpr` would work. Do you agree?

**Comment by ComicSansMS** [comment]
@elBoberido Alright, now things are getting subtle. The relevant section of the standard is [**[dcl.constexpr]**/5](https://raw.githubusercontent.com/cplusplus/draft/main/papers/n4140.pdf#subsection.7.1.5), which says:

> For a non-template, non-defaulted constexpr function [...], if no argument values exist such that an invocation of the function [...]
> could be an evaluated subexpression of a core constant expression (5.19), the program is ill-formed; no
> diagnostic required.

The problem is that according to [**[expr.const]**/2.2](https://raw.githubusercontent.com/cplusplus/draft/main/papers/n4140.pdf#section.5.19) invoking the non-`constexpr` functions inside `forwardPanic` prevents that function body from being a core constant expression, which makes it unconditionally if;ndr.

This restriction was removed in C++23 via [P2448](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2448r2.html), because it was becoming more and more useless as `constexpr` grew more powerful. I don't know of any compilers that actually silently accept this code as ill formed. But technically speaking, you need to provide some feasible execution path in every C++14 `constexpr` function that can actually be evaluated at compile time. `forwardPanic` in its current form does not do this.

**Comment by elBoberido** [comment]
@ComicSansMS understood. So the condition is required and this should be allowed https://godbolt.org/z/PM18YjM31
